### ISSUE TITLE
Custom Path not working

### ISSUE THREAD

**Issue by inumakieu** [brightdigit/PackageDSL#6]
im trying to add custom paths to my package logic, to organize it

But anytime i try to set it to `Sources/Features/\(self.name)`, or even a hardcoded name, it doesnt work
xcode complains that the logic should be in `Sources/\(self.name)`

example:
```swift
struct ChoutenApp: Product, Target {
    var name: String {
        "App"
    }

    var path: String? {
        "Sources/Features/\(self.name)"
    }

    var dependencies: any Dependencies {
        Architecture()
        More()
        ComposableArchitecture()
    }
}
```

**Comment by leogdion** [comment]
I just created a PR #7  for a new `Path:String?` property from branch `fix-path`. Can you try it out?
